@drawToken = (token) ->
  token_auto = if token.auto then " token-auto" else ""
  value = token.token_type
  token_class = ""

  if token.token_type == "variable"
    token_class = " token-variable"
    value = token.raw
  else if token.token_type == "number"
    token_class = " token-number"
    value = token.raw
  else if token.token_type == "left_paren"
    token_class = " token-paren"
    value = "("
  else if token.token_type == "right_paren"
    token_class = " token-paren"
    value = ")"
  else if token.token_type == "greater"
    token_class = " token-operator"
    value = ">"
  else if token.token_type == "less"
    token_class = " token-operator"
    value = "<"
  else if token.token_type == "greater_equal"
    token_class = " token-operator"
    value = ">="
  else if token.token_type == "less_equal"
    token_class = " token-operator"
    value = "<="
  else if token.token_type == "bang_equal"
    token_class = " token-operator"
    value = "!="
  else if token.token_type == "equal"
    token_class = " token-operator"
    value = "="
  else if token.token_type == "minus"
    token_class = " token-operator"
    value = "-"
  else if token.token_type == "plus"
    token_class = " token-operator"
    value = "+"
  else if token.token_type == "star"
    token_class = " token-operator"
    value = "*"
  else if token.token_type == "slash"
    token_class = " token-operator"
    value = "/"
  else if token.token_type == "bang"
    token_class = " token-operator"
    value = "!"

  "<span class=\"token#{token_auto}#{token_class}\">#{value}</span>"
