AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'db/schema.rb'
    # - 'config/**/*'
    # - 'script/**/*'
Rails:
  Enabled: true
# Style/Documentation:
#   Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
# Frozen String Literal Pragma will not be needed in Ruby 3+ as it will be the
# default, Added `frozen_string_literal: true` to use this new default
Style/FrozenStringLiteralComment:
  EnforcedStyle: always
# Strings assigned to constants will no longer be considered mutable in Ruby 3+
# This can be removed after Ruby 3 is released.
Style/MutableConstant:
  Enabled: false
Rails/DynamicFindBy:
  Whitelist:
    - find_by_param
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/InverseOf:
  Enabled: false

# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

# Allow perl backrefs.
Style/PerlBackrefs:
  Enabled: false

# Allow symbol arrays.
Style/SymbolArray:
  Enabled: false

# Allow word arrays.
Style/WordArray:
  Enabled: false

# Don't require brackets for white-space separated arrays.
Style/PercentLiteralDelimiters:
  Enabled: false

# Don't require formatted string tokens.
Style/FormatStringToken:
  Enabled: false
