# frozen_string_literal: true

require 'pats/categories/screen_failures/prev_upper_airway_surgery'
require 'pats/categories/screen_failures/dx_chronic_prob'
require 'pats/categories/screen_failures/recurrent_tonsillitis'
require 'pats/categories/screen_failures/hx_psych_behavioral_disorder'
require 'pats/categories/screen_failures/known_cond_airway'
require 'pats/categories/screen_failures/taking_meds'
require 'pats/categories/screen_failures/ent_eligibility_not_met'
require 'pats/categories/screen_failures/parent_report_snoring'
require 'pats/categories/screen_failures/previous_osa_diagnosis'
require 'pats/categories/screen_failures/psg_eligibility_not_met'
require 'pats/categories/screen_failures/bmi_z_score_le3'
require 'pats/categories/screen_failures/caregiver_understand_english'
require 'pats/categories/screen_failures/moving_in_year'
require 'pats/categories/screen_failures/foster_care'
