# frozen_string_literal: true

require 'pats/categories/psg_overall_study_qualities/psg_overall_study_quality_5'
require 'pats/categories/psg_overall_study_qualities/psg_overall_study_quality_4'
require 'pats/categories/psg_overall_study_qualities/psg_overall_study_quality_3'
require 'pats/categories/psg_overall_study_qualities/psg_overall_study_quality_2'
require 'pats/categories/psg_overall_study_qualities/psg_overall_study_quality_1'
require 'pats/categories/psg_overall_study_qualities/psg_overall_study_quality_0'
require 'pats/categories/psg_overall_study_qualities/psg_overall_study_quality_unknown'
